// Lets items in the home launcher list be pinned to the top.
// The <li> markup itself is regenerated by scripts/register-html.js, so
// pinning is applied at runtime here rather than baked into the HTML.
(function () {
    const STORAGE_KEY = 'imago-pinned-items';

    const STAR_SVG = `
        <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor"
             stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <path d="M12 2.8c.3 2.4.9 4.6 1.8 6.5 2.1.4 4.3.6 6.6 1-1.7 1.6-3.2 3.1-4.4 4.7.5 2.2.9 4.4 1 6.7-2-1.1-4-2.1-6-2.9-2 .9-4 1.9-6 2.9.2-2.3.6-4.5 1.1-6.7-1.3-1.5-2.8-3-4.5-4.6 2.3-.4 4.5-.7 6.6-1.1.8-1.9 1.4-4.1 1.8-6.5z"/>
        </svg>`;

    function getPinned() {
        try {
            const raw = JSON.parse(localStorage.getItem(STORAGE_KEY));
            return Array.isArray(raw) ? raw : [];
        } catch {
            return [];
        }
    }

    function setPinned(hrefs) {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(hrefs));
    }

    function keyFor(li) {
        const a = li.querySelector('a[href]');
        return a ? a.getAttribute('href') : null;
    }

    function togglePin(list, key) {
        const pinned = getPinned();
        const idx = pinned.indexOf(key);
        if (idx >= 0) pinned.splice(idx, 1);
        else pinned.push(key);
        setPinned(pinned);
        render(list);
    }

    function render(list) {
        const pinned = getPinned();
        const items = Array.from(list.querySelectorAll(':scope > li'));

        items.forEach(li => {
            const key = keyFor(li);
            const isPinned = pinned.includes(key);
            li.classList.toggle('pinned', isPinned);

            let btn = li.querySelector('.pin-btn');
            if (!btn) {
                btn = document.createElement('button');
                btn.type = 'button';
                btn.className = 'pin-btn';
                btn.innerHTML = STAR_SVG;
                btn.addEventListener('click', e => {
                    e.preventDefault();
                    e.stopPropagation();
                    togglePin(list, key);
                });
                li.appendChild(btn);
            }
            btn.classList.toggle('pinned', isPinned);
            btn.setAttribute('aria-pressed', String(isPinned));
            btn.setAttribute('aria-label', isPinned ? 'Unpin' : 'Pin to top');
        });

        const sorted = items.slice().sort((a, b) => {
            const aPinned = pinned.includes(keyFor(a));
            const bPinned = pinned.includes(keyFor(b));
            if (aPinned === bPinned) return 0;
            return aPinned ? -1 : 1;
        });
        sorted.forEach(li => list.appendChild(li));
    }

    document.addEventListener('DOMContentLoaded', () => {
        const list = document.querySelector('main ul');
        if (list) render(list);
    });
})();
